version: '3.7'
services:
  java-api:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    container_name: java-api
    depends_on:
      - mongo-db
  mongo-db:
    image: mongo
    ports:
      - "27017:27017"
    container_name: mongo-db